FROM node:latest

RUN useradd --user-group --create-home --shell /bin/false appuser

WORKDIR /home/appuser/app

COPY package*.json ./

RUN npm install

RUN chown -R appuser:appuser /home/appuser/app

USER appuser

COPY --chown=appuser:appuser . .

EXPOSE 3000

CMD ["npm", "run", "dev"]